CREATE SEQUENCE SEQ_CRIME
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOCACHE
NOCYCLE
;

CREATE TABLE TB_CRIME (
    ID_CRIME INTEGER DEFAULT SEQ_CRIME.NEXTVAL NOT NULL,
    TIPO VARCHAR(100) NOT NULL,
    DT_CRIME DATE NOT NULL,
    LOCALIZACAO VARCHAR(200) NOT NULL,
    DESCRICAO VARCHAR(500) NOT NULL,
    STATUS VARCHAR(50) NOT NULL
);