CREATE SEQUENCE SEQ_PATRULHA
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOCACHE
NOCYCLE
;

CREATE TABLE TB_PATRULHA (
    ID_PATRULHA INTEGER DEFAULT SEQ_PATRULHA.NEXTVAL NOT NULL,
    LOCALIZACAO VARCHAR(200) NOT NULL,
    DISPONIBILIDADE VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(500) NOT NULL
);