CREATE SEQUENCE SEQ_POLICIAL
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOCACHE
NOCYCLE
;

CREATE TABLE TB_POLICIAL (
    ID_POLICIAL INTEGER DEFAULT SEQ_POLICIAL.NEXTVAL NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CARGO VARCHAR(100) NOT NULL,
    DEPARTAMENTO VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL
);