CREATE SEQUENCE SEQ_USUARIO
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOCACHE
NOCYCLE
;

CREATE TABLE TB_USUARIO (
    ID_USUARIO INTEGER DEFAULT SEQ_USUARIO.NEXTVAL NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SENHA VARCHAR(20) NOT NULL,
    ROLE VARCHAR(50) DEFAULT 'USER'
);